
	.title	MENDE2

; demo playing .pt3 on menestrel (playing badly btw)

LOA_DONT_CLRSCR =: 1
@include aloader.mac

Main:	; vsync int off for 11M
	tst	@#100
	beq	02$
	mov	#40000, @#177662
02$:	; modify stop to shut VI's
	mov	#MainStop, Stop+2
	; hello world
	call	IniVis
	mov	#MsgHlo, R0
	call	Print

	mov	#177714, R5
10$:	mov	#^C^B1000000000000010, (R5)	; both chips, counter 0, value = 2
	mov	#^C^B1001000000000010, (R5)	; ~WR high
	wait
	mov	#^C^B1000000000000001, (R5)	; both chips, counter 0, value = 1
	mov	#^C^B1001000000000001, (R5)	; ~WR high
	wait
	br	10$

; init VI53 counters
IniVis:	mov	#177714, R0
	;            G  WDDAACCMLMMMB
	mov	#^C^B0000001100010100, (R0)	; both chips, counter 0, set mode 2, lsb (~WR low)
	mov	#^C^B0001001100010100, (R0)	; ~WR high
	mov	#^C^B0000001101010100, (R0)
	mov	#^C^B0001001101010100, (R0)
	mov	#^C^B0000001110010100, (R0)
	mov	#^C^B0001001110010100, (R0)
	return


; stop it
MainStop:
	call	IniVis
	jmp	Exit


; print something with emt's
; R0 - msg addr
Print:	cmp	@#100000, #167
	beq	10$
	cmpb	@#177717, #300
	bne	10$
	emt	65
	return
10$:	mov	R1, -(SP)
	mov	R2, -(SP)
	mov	R0, R1
	clr	R2
	emt	20
	mov	(SP)+, R1
	mov	(SP)+, R2
	return


; messages
MsgHlo:	.ascii	<12><15>"VI53 mode 2 test (STOP exit)"
MsgCrl:	.asciz	<12><15>
	.even

End:
	.end	Start
